### ISSUE TITLE
Trying to activate the layer manipulator on a 2D layer or while in 2D display results in a traceback

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari-threedee/napari-threedee#170] opened 2024-04-11 02:57 UTC
As the title says, if you try to activate the layer manipulator on a 2D layer you get a traceback.
Same for a 3D layer that is in 2D display.
It would be better to notify the user that it will only work in 3D -- I know, it's in the name napari-threedee, but still.

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File ~/Dev/miniforge3/envs/nap-3d/lib/python3.9/site-packages/app_model/backends/qt/_qaction.py:55, in QCommandAction._on_triggered(self=QMenuItemAction(MenuItem(when=None, group='3_plu...r (napari-threedee)'))), alt=None), app='napari'), checked=True)
     51 def _on_triggered(self, checked: bool) -> None:
     52     # execute_command returns a Future, for the sake of eventually being
     53     # asynchronous without breaking the API.  For now, we call result()
     54     # to raise any exceptions.
---> 55     self._app.commands.execute_command(self._command_id).result()
        self._command_id = 'napari-threedee:layer manipulator'
        self = QMenuItemAction(MenuItem(when=None, group='3_plugin_contributions', order=None, command=CommandRule(id='napari-threedee:layer manipulator', title='layer manipulator', category=None, tooltip=None, status_tip=None, icon=None, icon_visible_in_menu=True, enablement=None, short_title=None, toggled=ToggleRule(condition=None, get_current=functools.partial(<function _get_current_dock_status at 0x17c7e9940>, full_name='layer manipulator (napari-threedee)'))), alt=None), app='napari')
        self._app = Application('napari')

File ~/Dev/miniforge3/envs/nap-3d/lib/python3.9/site-packages/app_model/registries/_commands_reg.py:197, in CommandsRegistry.execute_command(self=<CommandsRegistry at 0x1050cae20 (123 commands)>, id='napari-threedee:layer manipulator', execute_asynchronously=False, *args=(), **kwargs={})
    193 except Exception as e:
    194     if self._raise_synchronous_exceptions:
    195         # note, the caller of this function can also achieve this by
    196         # calling `future.result()` on the returned future object.
--> 197         raise e
    198     future.set_exception(e)
    200 return future

File ~/Dev/miniforge3/envs/nap-3d/lib/python3.9/site-packages/app_model/registries/_commands_reg.py:192, in CommandsRegistry.execute_command(self=<CommandsRegistry at 0x1050cae20 (123 commands)>, id='napari-threedee:layer manipulator', execute_asynchronously=False, *args=(), **kwargs={})
    190 future: Future = Future()
    191 try:
--> 192     future.set_result(cmd(*args, **kwargs))
        future = <Future at 0x294e188b0 state=pending>
        cmd = <function Store.inject.<locals>._inner.<locals>._exec at 0x294978700>
        args = ()
        kwargs = {}
    193 except Exception as e:
    194     if self._raise_synchronous_exceptions:
    195         # note, the caller of this function can also achieve this by
    196         # calling `future.result()` on the returned future object.

File ~/Dev/miniforge3/envs/nap-3d/lib/python3.9/site-packages/in_n_out/_store.py:931, in Store.inject_processors.<locals>._deco.<locals>._exec(*args=(), **kwargs={})
    929 @wraps(func)
    930 def _exec(*args: P.args, **kwargs: P.kwargs) -> R:
--> 931     result = func(*args, **kwargs)
        func = <function Store.inject.<locals>._inner.<locals>._exec at 0x294949a60>
        args = ()
        kwargs = {}
    932     if result is not None:
    933         self.process(
    934             result,
    935             type_hint=type_hint,
   (...)
    938             _funcname=getattr(func, "__qualname__", str(func)),
    939         )

File ~/Dev/miniforge3/envs/nap-3d/lib/python3.9/site-packages/in_n_out/_store.py:801, in Store.inject.<locals>._inner.<locals>._exec(*args=(), **kwargs={})
    794 logger.debug(
    795     "  Calling %s with %r (injected %r)",
    796     _fname,
    797     bound.arguments,
    798     _injected_names,
    799 )
    800 try:
--> 801     result = func(**bound.arguments)
        bound = <BoundArguments (plugin='napari-threedee', widget_name='layer manipulator', full_name='layer manipulator (napari-threedee)')>
        func = functools.partial(<function _toggle_or_get_widget at 0x17c7e98b0>, plugin='napari-threedee', widget_name='layer manipulator', full_name='layer manipulator (napari-threedee)')
        bound.arguments = {'plugin': 'napari-threedee', 'widget_name': 'layer manipulator', 'full_name': 'layer manipulator (napari-threedee)'}
    802 except TypeError as e:
    803     if "missing" not in e.args[0]:

File ~/Dev/napari/napari/_qt/_qplugins/_qnpe2.py:351, in _toggle_or_get_widget(plugin='napari-threedee', widget_name='layer manipulator', full_name='layer manipulator (napari-threedee)')
    349 if widget_param:
    350     kwargs[widget_param] = viewer
--> 351 return widget_callable(**kwargs), full_name
        kwargs = {'viewer': Viewer(camera=Camera(center=(0.0, 255.5, 255.5), zoom=1.11142578125, angles=(0.0, 0.0, 90.0), perspective=0.0, mouse_pan=True, mouse_zoom=True), cursor=Cursor(position=(518.6754788398761, 579.8581504539962), scaled=True, style=<CursorStyle.STANDARD: 'standard'>, size=1.0), dims=Dims(ndim=2, ndisplay=2, order=(0, 1), axis_labels=('0', '1'), rollable=(True, True), range=(RangeTuple(start=0.0, stop=511.0, step=1.0), RangeTuple(start=0.0, stop=511.0, step=1.0)), margin_left=(0.0, 0.0), margin_right=(0.0, 0.0), point=(255.0, 255.0), last_used=0), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False), layers=[<Image layer 'astronaut' at 0x17fea8790>], help='use <2> for transform', status={'layer_name': 'astronaut', 'layer_base': 'astronaut', 'source_type': 'sample', 'plugin': 'napari builtins', 'coordinates': ' [519 580]'}, tooltip=Tooltip(visible=False, text=''), theme='dark', title='napari', mouse_over_canvas=True, mouse_move_callbacks=[], mouse_drag_callbacks=[], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x17c2dcb80>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, _keymap={})}
        widget_callable = <class 'napari_threedee.manipulators._qt.qt_layer_manipulator.QtLayerManipulatorWidget'>
        full_name = 'layer manipulator (napari-threedee)'

File ~/Dev/napari-threedee/src/napari_threedee/manipulators/_qt/qt_layer_manipulator.py:9, in QtLayerManipulatorWidget.__init__(self=<napari_threedee.manipulators._qt.qt_layer_manipulator.QtLayerManipulatorWidget object>, viewer=Viewer(camera=Camera(center=(0.0, 255.5, 255.5),...use_drag_gen={}, _mouse_wheel_gen={}, _keymap={}), *args=(), **kwargs={})
      8 def __init__(self, viewer: napari.Viewer, *args, **kwargs):
----> 9     super().__init__(model_class=LayerManipulator, viewer=viewer, *args, **kwargs)
        args = ()
        LayerManipulator = <class 'napari_threedee.manipulators.layer_manipulator.LayerManipulator'>
        viewer = Viewer(camera=Camera(center=(0.0, 255.5, 255.5), zoom=1.11142578125, angles=(0.0, 0.0, 90.0), perspective=0.0, mouse_pan=True, mouse_zoom=True), cursor=Cursor(position=(518.6754788398761, 579.8581504539962), scaled=True, style=<CursorStyle.STANDARD: 'standard'>, size=1.0), dims=Dims(ndim=2, ndisplay=2, order=(0, 1), axis_labels=('0', '1'), rollable=(True, True), range=(RangeTuple(start=0.0, stop=511.0, step=1.0), RangeTuple(start=0.0, stop=511.0, step=1.0)), margin_left=(0.0, 0.0), margin_right=(0.0, 0.0), point=(255.0, 255.0), last_used=0), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False), layers=[<Image layer 'astronaut' at 0x17fea8790>], help='use <2> for transform', status={'layer_name': 'astronaut', 'layer_base': 'astronaut', 'source_type': 'sample', 'plugin': 'napari builtins', 'coordinates': ' [519 580]'}, tooltip=Tooltip(visible=False, text=''), theme='dark', title='napari', mouse_over_canvas=True, mouse_move_callbacks=[], mouse_drag_callbacks=[], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x17c2dcb80>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, _keymap={})
        kwargs = {}

File ~/Dev/napari-threedee/src/napari_threedee/_backend/threedee_widget_base.py:23, in QtThreeDeeWidgetBase.__init__(self=<napari_threedee.manipulators._qt.qt_layer_manipulator.QtLayerManipulatorWidget object>, model_class=<class 'napari_threedee.manipulators.layer_manipulator.LayerManipulator'>, viewer=Viewer(camera=Camera(center=(0.0, 255.5, 255.5),...use_drag_gen={}, _mouse_wheel_gen={}, _keymap={}), flags=None, *args=(), **kwargs={})
     18 self.viewer = viewer
     20 self._layer_selection_widget = generate_populated_layer_selection_widget(
     21     func=self.model.set_layers, viewer=viewer
     22 )
---> 23 self._layer_selection_widget()
        self._layer_selection_widget = <FunctionGui set_layers(layer: napari.layers.base.base.Layer = <Image layer 'astronaut' at 0x17fea8790>)>
        self = <napari_threedee.manipulators._qt.qt_layer_manipulator.QtLayerManipulatorWidget object at 0x280885c10>
     25 # start in the disabled state
     26 self.model.enabled = False

File ~/Dev/miniforge3/envs/nap-3d/lib/python3.9/site-packages/magicgui/widgets/_function_gui.py:343, in FunctionGui.__call__(self=<FunctionGui set_layers(layer: napari.layers.bas...ayer = <Image layer 'astronaut' at 0x17fea8790>)>, *args=(), **kwargs={})
    341 self._tqdm_depth = 0  # reset the tqdm stack count
    342 with _function_name_pointing_to_widget(self):
--> 343     value = self._function(*bound.args, **bound.kwargs)
        self = <FunctionGui set_layers(layer: napari.layers.base.base.Layer = <Image layer 'astronaut' at 0x17fea8790>)>
        bound = <BoundArguments (layer=<Image layer 'astronaut' at 0x17fea8790>)>
        self._function = <bound method LayerManipulator.set_layers of <napari_threedee.manipulators.layer_manipulator.LayerManipulator object at 0x292aca160>>
    345 self._call_count += 1
    346 if self._result_widget is not None:

File ~/Dev/napari-threedee/src/napari_threedee/manipulators/layer_manipulator.py:15, in LayerManipulator.set_layers(self=<napari_threedee.manipulators.layer_manipulator.LayerManipulator object>, layer=<Image layer 'astronaut'>)
     14 def set_layers(self, layer: napari.layers.Layer):
---> 15     super().set_layers(layer)
        layer = <Image layer 'astronaut' at 0x17fea8790>

File ~/Dev/napari-threedee/src/napari_threedee/manipulators/base_manipulator.py:150, in BaseManipulator.set_layers(self=<napari_threedee.manipulators.layer_manipulator.LayerManipulator object>, layer=<Image layer 'astronaut'>)
    144 def set_layers(self, layer: Type[napari.layers.Layer]):
    145     """Add the correct layer type for the manipulator in a subclass.
    146 
    147     Implementing this method with a correct type annotation will allow
    148     autogeneration of a Qt widget for a manipulator.
    149     """
--> 150     self.layer = layer
        layer = <Image layer 'astronaut' at 0x17fea8790>
        self = <napari_threedee.manipulators.layer_manipulator.LayerManipulator object at 0x292aca160>

File ~/Dev/napari-threedee/src/napari_threedee/manipulators/base_manipulator.py:176, in BaseManipulator.layer(self=<napari_threedee.manipulators.layer_manipulator.LayerManipulator object>, layer=<Image layer 'astronaut'>)
    174 if self.layer is not None:
    175     self._disconnect_events()
--> 176 self._backend.layer = layer
        layer = <Image layer 'astronaut' at 0x17fea8790>
        self._backend = <napari_threedee._backend.manipulator.napari_manipulator_backend.NapariManipulatorBackend object at 0x280b55fa0>
        self = <napari_threedee.manipulators.layer_manipulator.LayerManipulator object at 0x292aca160>
    177 self._initialize_transform()
    178 if self.enabled:

File ~/Dev/napari-threedee/src/napari_threedee/_backend/manipulator/napari_manipulator_backend.py:56, in NapariManipulatorBackend.layer(self=<napari_threedee._backend.manipulator.napari_manipulator_backend.NapariManipulatorBackend object>, layer=<Image layer 'astronaut'>)
     54     self._disconnect_mouse_callback()
     55 self._layer = layer
---> 56 self._connect_vispy_visual()
        self = <napari_threedee._backend.manipulator.napari_manipulator_backend.NapariManipulatorBackend object at 0x280b55fa0>
     57 self._connect_mouse_callback()

File ~/Dev/napari-threedee/src/napari_threedee/_backend/manipulator/napari_manipulator_backend.py:71, in NapariManipulatorBackend._connect_vispy_visual(self=<napari_threedee._backend.manipulator.napari_manipulator_backend.NapariManipulatorBackend object>)
     69 self.vispy_visual.parent = parent
     70 self.vispy_visual.transform = MatrixTransform()
---> 71 self.vispy_visual.canvas._backend.destroyed.connect(self._set_canvas_none)
        self.vispy_visual = <ManipulatorVisual at 0x280b4d490>
        self = <napari_threedee._backend.manipulator.napari_manipulator_backend.NapariManipulatorBackend object at 0x280b55fa0>

AttributeError: 'NoneType' object has no attribute '_backend'
```

**Comment by alisterburt** [comment] 2024-04-11 03:04
duplicate of #169

**Closed** 2024-07-04 18:53 UTC
